# version: "3.9"

services:
  postgres:
    image: postgres:16-alpine
    container_name: musicvote-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: musicuser
      POSTGRES_PASSWORD: musicpass
      POSTGRES_DB: musicvote
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U musicuser -d musicvote"]
      interval: 5s
      timeout: 5s
      retries: 10

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: musicvote-backend
    restart: unless-stopped
    env_file:
      - ./backend/.env.prod
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "4000:4000"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: musicvote-frontend
    restart: unless-stopped
    environment:
      # Utilisé seulement au build Vite
      - VITE_API_URL=http://localhost:4000
    ports:
      - "8080:80"
    depends_on:
      - backend

volumes:
  postgres_data:
